import assert from 'node:assert/strict'; import test from 'node:test';
import { applicableQuestions, conditionalQuestions, coreQuestions, healthTracks, questions } from '../src/data.ts';
import { buildEngineSubmission, calculateResults, clearInapplicableAnswers, hasCompleteAssessment, normalizedScore, PROGRESS_KEY } from '../src/assessment.ts';
import { ASSESSMENT_VERSION, type Answers, type BusinessContext } from '../src/types.ts';
const context:BusinessContext={desiredModel:'Owner-led specialist',teamSituation:'Solo owner',ownerReliance:'Almost everything',priority:'More profitable work'};
const filled=(hasTeam=false,value=3)=>Object.fromEntries(applicableQuestions(hasTeam).map(q=>[q.id,value])) as Answers;
test('V2 contract has exact version, 19 core, one conditional and six tracks',()=>{assert.equal(ASSESSMENT_VERSION,'tradebuilt-contractor-health-check-v2.0');assert.equal(coreQuestions.length,19);assert.equal(conditionalQuestions.length,1);assert.equal(conditionalQuestions[0].id,'TB-CAP-03');assert.deepEqual(healthTracks,['Delivery & Workmanship','Client Experience & Communication','Commercial Control','Financial Control','Demand & Positioning','Capacity & Direction']);assert.equal(new Set(questions.map(q=>q.id)).size,20)});
test('solo excludes crew evidence while team requires it and stale data clears',()=>{assert.equal(applicableQuestions(false).length,19);assert.equal(applicableQuestions(true).length,20);assert.equal(hasCompleteAssessment(filled(false),false),true);assert.equal(hasCompleteAssessment(filled(false),true),false);assert.equal(clearInapplicableAnswers({...filled(false),'TB-CAP-03':4},false)['TB-CAP-03'],undefined)});
test('normalizes four-point scale and excludes materials N/A from evidence',()=>{assert.deepEqual([1,2,3,4].map(normalizedScore),[0,33,67,100]);const a=filled(false,4);a['TB-FIN-02']=null;const r=calculateResults(a,context,false);assert.equal(r.tracks.find(t=>t.track==='Financial Control')?.applicableEvidence,2);assert.equal(r.tracks.find(t=>t.track==='Financial Control')?.score,100)});
test('scores equal-weight tracks from applicable scored evidence',()=>{const r=calculateResults(filled(false,3),context,false);assert.equal(r.overall,68);assert.equal(r.tracks.length,6);assert.match(r.disclaimer,/directional, self-reported/)});
test('QS and detailed internal costing are equally strong scoring signals',()=>{const detailed=filled();const qs=filled();detailed['TB-COM-02']=3;qs['TB-COM-02']=4;assert.equal(calculateResults(detailed,context,false).tracks.find(t=>t.track==='Commercial Control')?.score,calculateResults(qs,context,false).tracks.find(t=>t.track==='Commercial Control')?.score)});
test('owner-led specialist is not penalised but model mismatch is flagged',()=>{const a=filled();assert.equal(calculateResults(a,context,false).risks.some(x=>/owner reliance/.test(x)),false);assert.equal(calculateResults(a,{...context,desiredModel:'Team-led business'},false).risks.some(x=>/owner reliance/.test(x)),true)});
test('low pricing confidence only flags investigation and never says raise prices',()=>{const a=filled();a['TB-COM-02']=1;const text=JSON.stringify(calculateResults(a,context,false));assert.match(text,/Pricing and value alignment needs deeper investigation/);assert.doesNotMatch(text,/raise (your )?prices/i)});
test('engine payload includes context, follow-up and conditional state',()=>{const p=buildEngineSubmission('stable-id',filled(false),context,false,'Google',{name:'Pat'});assert.equal(p.assessmentVersion,ASSESSMENT_VERSION);assert.equal(p.product,'TRADEBUILT');assert.equal(p.answers.length,19);assert.equal(p.answers.some(a=>a.questionId==='TB-CAP-03'),false);assert.equal(p.answers.find(a=>a.questionId==='TB-FIN-02')?.rawType,'SINGLE_SELECT');assert.equal(p.leadSource,'Google');assert.equal(p.crewQuestionShown,false);assert.deepEqual(p.leadProfile,{name:'Pat'});assert.doesNotMatch(JSON.stringify(p),/brand.blueprint|BBP/i);assert.match(PROGRESS_KEY,/v2\.0/)});

test('completed V1 uses frozen legacy interpretation and is not relabelled V2',async()=>{const {interpretCompletedV1,LEGACY_V1_VERSION}=await import('../src/legacyV1.ts');const answers=Object.fromEntries(Array.from({length:25},(_,i)=>[i+1,3]));const map=Object.fromEntries(Array.from({length:25},(_,i)=>[i+1,i<3?'Pricing':'Operations']));const result=interpretCompletedV1(answers,map);assert.equal(result.version,LEGACY_V1_VERSION);assert.equal(result.overall,60);assert.notEqual(result.version,ASSESSMENT_VERSION)});
