import { FormEvent, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { applicableQuestions, questions } from './data';
import { buildEngineSubmission, calculateResults, clearInapplicableAnswers, hasCompleteAssessment, PROGRESS_KEY } from './assessment';
import { createPdfReport } from './pdfReport';
import type { Answers, BusinessContext, LeadProfile } from './types';

type Screen = 'intro'|'context'|'assessment'|'gate'|'results';
const initialContext: BusinessContext = { desiredModel: 'Owner-led specialist', teamSituation: 'Solo owner', ownerReliance: 'Everything', priority: '' };
const initialLead: LeadProfile = { name:'',company:'',email:'',phone:'',trade:'' };
const post = async (url:string, body:unknown) => { const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(!response.ok) throw new Error('Delivery failed'); };

export default function App() {
  const [screen,setScreen]=useState<Screen>('intro'); const [context,setContext]=useState(initialContext); const [answers,setAnswers]=useState<Answers>({}); const [index,setIndex]=useState(0); const [lead,setLead]=useState(initialLead); const [notice,setNotice]=useState('');
  const hasTeam=context.teamSituation!=='Solo owner'; const active=applicableQuestions(hasTeam); const result=useMemo(()=>calculateResults(answers,context,hasTeam),[answers,context,hasTeam]);
  const choose=(value:string|number|boolean|null)=>{ const next={...answers,[active[index].id]:value}; setAnswers(next); localStorage.setItem(PROGRESS_KEY,JSON.stringify({version:'tradebuilt-contractor-health-check-v2.0',context,answers:next,index})); if(index===active.length-1){ if(hasCompleteAssessment(next,hasTeam)) setScreen('gate'); } else setIndex(index+1); };
  const updateContext=(patch:Partial<BusinessContext>)=>{ const next={...context,...patch}; setContext(next); const team=next.teamSituation!=='Solo owner'; setAnswers((current)=>clearInapplicableAnswers(current,team)); setIndex(0); };
  const reveal=async(e:FormEvent)=>{e.preventDefault(); if(!lead.name.trim()||!/^\S+@\S+\.\S+$/.test(lead.email)){setNotice('Name and a valid email are required.');return;} const submissionId=sessionStorage.getItem('tradebuilt:v2:submission-id')??crypto.randomUUID(); sessionStorage.setItem('tradebuilt:v2:submission-id',submissionId); const engine=buildEngineSubmission(submissionId,answers,context,hasTeam); localStorage.removeItem(PROGRESS_KEY); setScreen('results'); post('/api/engine-ingestion',engine).catch(()=>{}); try { const pdf=createPdfReport(lead,result,context); const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]??'');r.onerror=reject;r.readAsDataURL(pdf.blob)}); await post('/api/email-report',{leadProfile:lead,results:result,context,completedAt:new Date().toISOString(),pdf:{base64,filename:pdf.filename}}); setNotice('Your report has been emailed.'); } catch { setNotice('Your result is ready. Email delivery was unavailable; you can still download it below.'); }};
  if(screen==='intro') return <Page variant="intro"><h1>TradeBuilt Contractor Health Check</h1><p className="intro-copy">A free directional check of six areas of contractor business health.</p><button onClick={()=>setScreen('context')}>Start the Health Check <span className="button-arrow" aria-hidden="true">→</span></button><p className="question-count">19 core questions, plus one question when you have staff or crew.</p></Page>;
  if(screen==='context') return <Page><h1>About your business</h1><Field label="Desired business model"><select value={context.desiredModel} onChange={e=>updateContext({desiredModel:e.target.value})}><option>Owner-led specialist</option><option>Owner-led team</option><option>Team-led business</option></select></Field><Field label="Current team or crew"><select value={context.teamSituation} onChange={e=>updateContext({teamSituation:e.target.value})}><option>Solo owner</option><option>Staff or crew</option></select></Field><Field label="How reliant is the business on you today?"><select value={context.ownerReliance} onChange={e=>updateContext({ownerReliance:e.target.value})}><option>Everything</option><option>Most decisions and delivery</option><option>Selected specialist work</option><option>Limited day-to-day reliance</option></select></Field><Field label="Main priority or goal"><input value={context.priority} onChange={e=>setContext({...context,priority:e.target.value})}/></Field><button onClick={()=>setScreen('assessment')}>Continue</button></Page>;
  if(screen==='assessment'){const question=active[index]; const progress=`${((index+1)/active.length)*100}%`; return <Page><div className="progress-meta"><span>{question.track}</span><span>Question {index+1} of {active.length}</span></div><div className="progress-track" style={{'--progress':progress} as CSSProperties} aria-hidden="true"><span /></div><h1 className="question-title">{question.prompt}</h1><div className="options">{question.options.map(option=><button key={String(option.value)} onClick={()=>choose(option.value)}>{option.label}</button>)}</div>{index>0&&<button className="secondary" onClick={()=>setIndex(index-1)}>Back</button>}</Page>}
  if(screen==='gate') return <Page><h1>Your Health Check is complete</h1><p>Enter your contact details immediately before revealing and sending the full result.</p><form onSubmit={reveal}><Field label="Name"><input required value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/></Field><Field label="Email"><input required type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/></Field><Field label="Business name"><input value={lead.company} onChange={e=>setLead({...lead,company:e.target.value})}/></Field><Field label="Trade"><input value={lead.trade} onChange={e=>setLead({...lead,trade:e.target.value})}/></Field><Field label="Phone (optional)"><input value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/></Field><button>Reveal my result</button>{notice&&<p role="alert">{notice}</p>}</form></Page>;
  return <Page variant="results"><p className="eyebrow">TRADEBUILT · CONTRACTOR HEALTH CHECK</p><h1>{result.overall}<small>/100</small></h1><p className="disclaimer">{result.disclaimer}</p>{notice&&<p>{notice}</p>}<h2>Six health tracks</h2>{result.tracks.map(t=><div className="score" key={t.track}><strong>{t.track}</strong><span>{t.score}/100</span></div>)}<Columns title="Strongest areas" values={result.strengths}/><Columns title="Weakest areas" values={result.weaknesses}/><Columns title="Likely risks" values={result.risks}/><Columns title="Priority investigation areas" values={result.investigationPriorities}/><Columns title="Areas requiring deeper evidence" values={result.deeperEvidence}/><p>The next step is a TradeBuilt paid diagnostic to investigate evidence and establish root causes before strategy or implementation.</p><button onClick={()=>{const p=createPdfReport(lead,result,context);const a=document.createElement('a');a.href=URL.createObjectURL(p.blob);a.download=p.filename;a.click()}}>Download PDF</button></Page>;
}
function Page({children,variant}:{children:React.ReactNode;variant?:'intro'|'results'}){return <main><div className="shell"><header className="brand-bar"><div className="wordmark" aria-label="TradeBuilt"><span className="wordmark-mark" aria-hidden="true"/>TRADEBUILT</div></header><section className={`card${variant?` card--${variant}`:''}`}>{children}</section></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span>{label}</span>{children}</label>}
function Columns({title,values}:{title:string;values:string[]}){return <section className="report-section"><h2>{title}</h2><ul>{values.map(v=><li key={v}>{v}</li>)}</ul></section>}
export { questions, calculateResults };
