import { FormEvent, useMemo, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import { applicableQuestions, questions } from './data';
import { buildEngineSubmission, calculateResults, clearInapplicableAnswers, hasCompleteAssessment, PROGRESS_KEY } from './assessment';
import { createPdfReport } from './pdfReport';
import type { Answers, BusinessContext, LeadProfile } from './types';

type Screen = 'intro'|'context'|'assessment'|'gate'|'results';
const initialContext: BusinessContext = { desiredModel: 'Owner-led specialist', teamSituation: 'Solo owner', ownerReliance: 'Almost everything', priority: 'More profitable work' };
const initialLead: LeadProfile = { name:'',company:'',email:'',phone:'',trade:'' };
const post = async (url:string, body:unknown) => { const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(!response.ok) throw new Error('Delivery failed'); };

export default function App() {
  const [screen,setScreen]=useState<Screen>('intro'); const [context,setContext]=useState(initialContext); const [answers,setAnswers]=useState<Answers>({}); const [index,setIndex]=useState(0); const [leadSource,setLeadSource]=useState(''); const [lead,setLead]=useState(initialLead); const [notice,setNotice]=useState(''); const [submitting,setSubmitting]=useState(false); const advanceTimer=useRef<number|undefined>(undefined);
  const hasTeam=context.teamSituation!=='Solo owner'; const active=applicableQuestions(hasTeam); const result=useMemo(()=>calculateResults(answers,context,hasTeam),[answers,context,hasTeam]);
  const advance=(next:Answers)=>{ window.clearTimeout(advanceTimer.current); advanceTimer.current=window.setTimeout(()=>{ if(index===active.length-1){ if(hasCompleteAssessment(next,hasTeam)) setScreen('gate'); } else setIndex(index+1); },180); };
  const choose=(value:string|number|boolean|null)=>{ const question=active[index]; const next={...answers,[question.id]:value}; setAnswers(next); localStorage.setItem(PROGRESS_KEY,JSON.stringify({version:'tradebuilt-contractor-health-check-v2.0',context,answers:next,index})); if(question.id==='TB-DEM-03'&&(value===3||value===4)) return; if(question.id==='TB-DEM-03') setLeadSource(''); advance(next); };
  const updateContext=(patch:Partial<BusinessContext>)=>{ const next={...context,...patch}; setContext(next); const team=next.teamSituation!=='Solo owner'; setAnswers((current)=>clearInapplicableAnswers(current,team)); setIndex(0); };
  const goBack=()=>{ window.clearTimeout(advanceTimer.current); setIndex(index-1); };
  const reveal=async(e:FormEvent)=>{e.preventDefault(); if(!lead.name.trim()||!/^\S+@\S+\.\S+$/.test(lead.email)){setNotice('Name and a valid email are required.');return;} setSubmitting(true); setNotice(''); const submissionId=sessionStorage.getItem('tradebuilt:v2:submission-id')??crypto.randomUUID(); sessionStorage.setItem('tradebuilt:v2:submission-id',submissionId); const engine=buildEngineSubmission(submissionId,answers,context,hasTeam,leadSource,lead,result); try { const pdf=createPdfReport(lead,result,context); const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=reject;reader.readAsDataURL(pdf.blob)}); await post('/api/email-report',{leadProfile:lead,results:result,context,answers:engine.answers,leadSource,crewQuestionShown:hasTeam,completedAt:new Date().toISOString(),pdf:{base64,filename:pdf.filename}}); localStorage.removeItem(PROGRESS_KEY); post('/api/engine-ingestion',engine).catch(()=>{}); setScreen('results'); } catch { setNotice('We could not confirm email delivery. Please try submitting again.'); setSubmitting(false); } };
  if(screen==='intro') return <Page variant="intro"><h1>TradeBuilt<br />Contractor Health Check<span className="heading-full-stop">.</span></h1><p className="intro-copy">A quick check of the six areas that shape a stronger, more profitable contracting business.</p><button onClick={()=>setScreen('context')}>Start Health Check <span className="button-arrow" aria-hidden="true">→</span></button><p className="question-count">About 5 minutes · up to 20 questions</p></Page>;
  if(screen==='context') return <Page><h1>About your business</h1><Field label="Desired business model"><select value={context.desiredModel} onChange={e=>updateContext({desiredModel:e.target.value})}><option>Owner-led specialist</option><option>Small crew / owner-managed</option><option>Established team</option><option>Multi-team contracting business</option><option>Not sure yet</option></select></Field><Field label="Current team or crew"><select value={context.teamSituation} onChange={e=>updateContext({teamSituation:e.target.value})}><option>Solo owner</option><option>1–3 people</option><option>4–10 people</option><option>11–20 people</option><option>20+</option></select></Field><Field label="How reliant is the business on you today?"><select value={context.ownerReliance} onChange={e=>updateContext({ownerReliance:e.target.value})}><option>Almost everything</option><option>Most things</option><option>About half</option><option>Mainly key decisions</option><option>Very little</option></select></Field><Field label="Main priority right now"><select value={context.priority} onChange={e=>setContext({...context,priority:e.target.value})}><option>More profitable work</option><option>More consistent work</option><option>Better margins / cash flow</option><option>Better systems</option><option>Build a stronger team</option><option>Reduce dependence on me</option><option>Grow the business</option><option>Other</option></select></Field><button onClick={()=>setScreen('assessment')}>Continue</button></Page>;
  if(screen==='assessment'){const question=active[index]; const progress=`${((index+1)/active.length)*100}%`; const needsLeadSource=question.id==='TB-DEM-03'&&(answers[question.id]===3||answers[question.id]===4); return <Page><div className="progress-meta"><span>{question.track}</span><span>Question {index+1} of {active.length}</span></div><div className="progress-track" style={{'--progress':progress} as CSSProperties} aria-hidden="true"><span /></div><h1 className="question-title">{question.prompt}</h1><div className="options">{question.options.map(option=><button className={answers[question.id]===option.value?'selected':undefined} aria-pressed={answers[question.id]===option.value} key={String(option.value)} onClick={()=>choose(option.value)}>{option.label}</button>)}</div>{needsLeadSource&&<div className="follow-up"><Field label="Where do your best enquiries come from?"><input autoFocus value={leadSource} onChange={e=>setLeadSource(e.target.value)}/></Field><button onClick={()=>advance(answers)}>Continue</button></div>}{index>0&&<button className="secondary" onClick={goBack}>Back</button>}</Page>}
  if(screen==='gate') return <Page><h1>Your Health Check is complete<span className="heading-full-stop">.</span></h1><p>Enter your contact details so I can personally review your answers.</p><form onSubmit={reveal}><Field label="Name"><input required value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/></Field><Field label="Email"><input required type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/></Field><Field label="Business name"><input value={lead.company} onChange={e=>setLead({...lead,company:e.target.value})}/></Field><Field label="Trade"><input value={lead.trade} onChange={e=>setLead({...lead,trade:e.target.value})}/></Field><Field label="Phone (optional)"><input value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/></Field><button disabled={submitting}>{submitting?'Sending…':'Submit Health Check'}</button>{notice&&<p role="alert">{notice}</p>}</form></Page>;
  return <Page variant="results"><h1>Thanks - got it.</h1><p className="completion-lead">I will read your message and reply directly. In the meantime, the free Health Check can help you clarify what needs attention first.</p><section className="quick-guide"><p className="eyebrow">WHILE YOU WAIT</p><h2>Get the TradeBuilt Quick Guide</h2><p>Five things every contractor should have under control.</p><div className="completion-actions"><a className="button-link" href="/tradebuilt-quick-guide.pdf" target="_blank" rel="noreferrer" download>Download the Free Quick Guide</a><a className="website-link" href="https://www.tradebuilt.pro/">← Back to TradeBuilt website</a></div></section></Page>;
}
function Page({children,variant}:{children:React.ReactNode;variant?:'intro'|'results'}){return <main><div className="shell"><header className="brand-bar"><a href="https://www.tradebuilt.pro/"><img className="brand-wordmark" src="/tradebuilt-logo-cream.png" alt="TradeBuilt" /></a></header><section className={`card${variant?` card--${variant}`:''}`}>{children}</section></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span>{label}</span>{children}</label>}
export { questions, calculateResults };
